### ISSUE TITLE
Releases not updated

### ISSUE THREAD

**Issue by hankache** [MoarVM/moarvm.org#9]
The moarvm.org website lists 2017.09 as the latest release.
Three releases are not listed (2017.10 2017.11 and 2017.12)

**Comment by hankache** [comment]
This should be partly resolved by #10   
The home page (index.html) need to list the latest release and a small summary of changes.

**Comment by samcv** [comment]
This has been fixed since I added an automated tool to update the site: https://github.com/MoarVM/MoarVM/blob/master/tools/moarvm.org_releases.pl

Closing.
